name: Release Official Docker Image

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/blockchain_insights_base
          VERSION=${{ github.event.inputs.version || github.event.release.tag_name }}
          VERSION_TAG="$IMAGE_NAME:$VERSION"
          LATEST_TAG="$IMAGE_NAME:latest"
          # Build the Docker image with the version tag
          docker build --tag $VERSION_TAG .
          # Tag the same image with the 'latest' tag
          docker tag $VERSION_TAG $LATEST_TAG
          # Push both the version tag and the latest tag
          docker push $VERSION_TAG
          docker push $LATEST_TAG
